apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: signite
type: Opaque
data:
  username: c2lnbml0ZQ==  # signite (base64 encoded)
  password: c2lnbml0ZQ==  # signite (base64 encoded)
  auth-service-url: bXlzcWw6Ly9zaWduaXRlOnNpZ25pdGVAbXlzcWwuc2lnbml0ZS5zdmM6MzMwNi9hdXRoX2Ri  # mysql://signite:signite@mysql.signite.svc:3306/auth_db
  sigboard-jdbc-url: amRiYzpteXNxbDovL215c3FsLnNpZ25pdGUuc3ZjOjMzMDYvc2lnYm9hcmRfZGI=  # jdbc:mysql://mysql.signite.svc:3306/sigboard_db
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: signite
type: Opaque
data:
  secret: c2lnbml0ZS1qd3Qtc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbg==  # signite-jwt-secret-key-for-production 