apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: signite
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ${AWS_ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/signite/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8081"
        - name: GRPC_PORT
          value: "50051"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: auth-service-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: JWT_EXPIRES_IN
          value: "3600"
        - name: RUST_LOG
          value: "info"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_USER_EVENTS_TOPIC
          value: "user-events"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20 