apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: signite
spec:
  selector:
    app: auth-service
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: grpc
    port: 50051
    targetPort: grpc
  type: ClusterIP 