apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigboard-service
  namespace: signite
  labels:
    app: sigboard-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sigboard-service
  template:
    metadata:
      labels:
        app: sigboard-service
    spec:
      containers:
      - name: sigboard-service
        image: ${AWS_ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/signite/sigboard-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: sigboard-jdbc-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "com.mysql.cj.jdbc.Driver"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: AUTH_SERVICE_GRPC_HOST
          value: "auth-service"
        - name: AUTH_SERVICE_GRPC_PORT
          value: "50051"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: "sigboard-service"
        - name: KAFKA_USER_EVENTS_TOPIC
          value: "user-events"
        - name: KAFKA_DOCUMENT_EVENTS_TOPIC
          value: "document-events"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20 