apiVersion: v1
kind: Service
metadata:
  name: sigboard-service
  namespace: signite
spec:
  selector:
    app: sigboard-service
  ports:
  - name: http
    port: 80
    targetPort: http
  type: ClusterIP 